# @package _global_
defaults:
  - dataset_module: dataset
  - architecture_module: basic_archimodule
  - hydra: hydra

project_dir: C:/Users/ddang/Desktop/projects/ai-lab-eda

data_path: ${project_dir}/data
data_type: binary_imbalanced
data_name: ${data_type}_test.csv
meaningful_features:
  - HighBP
  - HighChol
  - CholCheck
  - BMI
  - Smoker
  - Stroke
  - HeartDiseaseorAttack
  - PhysActivity
  - Fruits
  - Veggies
  - HvyAlcoholConsump
  - AnyHealthcare
  - NoDocbcCost
  - GenHlth
  - MentHlth
  - PhysHlth
  - DiffWalk
  - Sex
  - Age
  - Education
  - Income
model_save_path: ${project_dir}/save_model/basic_classifier/all_features/${data_type}
result_path: ${project_dir}/result_reports

result_name: basic_all_features_test_result.csv

run_name: basic_test
work_dir: ${hydra:runtime.cwd}