# @package _global_
defaults:
  - dataset: diabetes_dataset
  - architecture: lgbm_architecture
  - hydra: hydra

project_dir: C:/Users/ddang/Desktop/projects/ai-lab-eda

data_path: ${project_dir}/data
data_type: all_data
data_name: ${data_type}_test.csv
meaningful_features:
  - HighBP
  - HighChol
  - CholCheck
  - BMI
  - Smoker
  - Stroke
  - HeartDiseaseorAttack
  - PhysActivity
  - Fruits
  - Veggies
  - HvyAlcoholConsump
  - AnyHealthcare
  - NoDocbcCost
  - GenHlth
  - MentHlth
  - PhysHlth
  - DiffWalk
  - Sex
  - Age
  - Education
  - Income

model_name: lgbm
features: all_features

model_save_path: ${project_dir}/save_model/${model_name}/${data_type}/${features}
result_path: ${project_dir}/result_reports/${model_name}

result_name: ${model_name}_${features}_test_result.csv

project_name: LGBMClassifier

run_name: ${tags}-test
work_dir: ${hydra:runtime.cwd}

tags: ${project_name}-diabetes-${features}