# @package _global_
defaults:
  - dataset: diabetes_dataset
  - tuner: xgb_tuner
  - hydra: hydra

project_dir: C:/Users/ddang/Desktop/projects/ai-lab-eda

data_path: ${project_dir}/data
data_type: all_data
data_name: ${data_type}_train.csv
meaningful_features:
  - HighBP
  - HighChol
  - CholCheck
  - BMI
  - Smoker
  - Stroke
  - HeartDiseaseorAttack
  - PhysActivity
  - Fruits
  - Veggies
  - HvyAlcoholConsump
  - AnyHealthcare
  - NoDocbcCost
  - GenHlth
  - MentHlth
  - PhysHlth
  - DiffWalk
  - Sex
  - Age
  - Education
  - Income

split_size: 0.2
num_folds: 10
metric: f1
num_trials: 100
seed: 2024
tuning_way: original
model_name: xgb
save_path: ${project_dir}/hparams

project_name: XGBClassifier

run_name: ${tags}-tune
work_dir: ${hydra:runtime.cwd}

tags: ${project_name}-diabetes-tuning_way_{tuning_way}-metric_{metric}-num_trials{num_trials}