_target_: src.statistics_modules.statistical_analysis.StatisticalAnalysis
df_path: ${project_dir}/${dataset_path}/${dataset}
features: ${features}
method: ${method}
result_path: ${project_dir}/result_reports/statistics
result_name: analyze_statistics_results.csv